stages:
  - test
  - secret-detection
  - deploy

sast:
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  SECRET_DETECTION_ENABLED: 'true'

secret_detection:
  stage: secret-detection

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r aluno professor shared index.html logo.png manifest.webmanifest sw.js public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
